name: knox
description: An implementation of HydratedStorage using flutter_secure_storage, which interfaces with Keychain (iOS) and KeyStore (Android)
version: 1.0.0
homepage: https://github.com/arnemolland/knox

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^3.3.1+1
  hydrated_bloc: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
